name: GCP Docker Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  DOCKER_BUILDKIT: 1
  PROJECT_ID: hackher-416720 # TODO: update Google Cloud project id
  SERVICE: hackherstreamlit # TODO: update Cloud Run service name
  REGION: us-central1 # TODO: update Cloud Run service region

jobs:
  build-and-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Create JSON file'
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > GOOGLE_APPLICATION_CREDENTIALS.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --file ./Dockerfile --tag jamesliangg/hackher:${{ github.sha }} --push .

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: docker.io/jamesliangg/hackher:${{ github.sha }}
          env_vars: |
            GOOGLE_APPLICATION_CREDENTIALS=GOOGLE_APPLICATION_CREDENTIALS.json
            REDIS_URL=${{ secrets.REDIS_URL }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}